dataset:
  rows: 50
  composition_percentage:
    duplicates: 0
    missing_fields: 0
    unprocessable_rows: 0
    late_rows_percentage: 50
data_blocker:
  type: 'sleep'
  configuration:
    sleep_time_range_seconds:
      from: 1
      to: 7
entity:
  type: visit
  configuration:
    start_time: '2023-11-01T00:00:00Z'
generator:
  type: continuous
writer:
  type: kafka
  configuration:
    broker: 'kafka:9092'
    output_topic: 'visits'
    extra_producer_config:
      'queue.buffering.max.ms': 2000
