version: '3.1'
services:
  data_generator:
    image: waitingforcode/data-generator-blogging-platform:0.1-beta
    container_name: dedp_test_full_loader_exposition
    volumes:
      - /tmp/dedp/ch02/full-loader/data-exposition:/home/data_generator_user/data_generator_output
      - ./generation_configuration.yaml:/home/data_generator_user/generation_configuration.yaml
    entrypoint:
      - python3
      - /home/data_generator_user/data_generator/generate_dataset.py
      - --config_file
      - /home/data_generator_user/generation_configuration.yaml
