dataset:
  rows: 1000
  composition_percentage:
    duplicates: 0
    missing_fields: 0
    unprocessable_rows: 0
  late_rows_percentage: 70
data_blocker:
  type: 'no'
entity:
  type: visit
  configuration:
    start_time: '2023-11-01T00:00:00Z'
generator:
  type: one-shot
writer:
  type: json
  configuration:
    output_path: '/home/data_generator_user/data_generator_output/input'
    clean_path: true
  partitions: ['date=2023-11-01', 'date=2023-11-02', 'date=2023-11-03', 'date=2023-11-04',
               'date=2023-11-05', 'date=2023-11-06', 'date=2023-11-07']
